apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: myportfoliowebsite
  annotations:
    description: "Production pipeline for My Portfolio Website"
    environment: "production"
serialPipeline:
  stages:
  - targetId: newportfolio-prod
    profiles: ["prod"]

executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: 622922749626-compute@developer.gserviceaccount.com
  executionTimeout: 3600s

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: newportfolio-prod
  annotations:
    description: "Production target for My Portfolio Website"
    environment: "production"
gke:
  cluster: projects/${PROJECT_ID}/locations/asia-east1/clusters/newportfolio
  internalIp: false
  requireApproval: false
  runAs: 622922749626-compute@developer.gserviceaccount.com 