steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/coherent-coder-460505-m1/myportartifacts/portfolio-website:$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/coherent-coder-460505-m1/myportartifacts/portfolio-website:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'portfolio-website1'
  - '--image'
  - 'gcr.io/coherent-coder-460505-m1/myportartifacts/portfolio-website:$COMMIT_SHA'
  - '--region'
  - 'europe-central2'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'EMAIL_USER=${_EMAIL_USER},EMAIL_PASS=${_EMAIL_PASS}'

images:
- 'gcr.io/coherent-coder-460505-m1/myportartifacts/portfolio-website:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _EMAIL_USER: ''  # Will be set in Cloud Build trigger
  _EMAIL_PASS: ''  # Will be set in Cloud Build trigger 