steps:
# Validate configuration files
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Validating configuration files..."
    # Check if the files exist
    if [ ! -f "clouddeploy.yaml" ]; then
      echo "Error: clouddeploy.yaml not found"
      exit 1
    fi
    if [ ! -f "skaffold.yaml" ]; then
      echo "Error: skaffold.yaml not found"
      exit 1
    fi
    # Validate YAML syntax
    if ! gcloud deploy apply --file=clouddeploy.yaml --region=asia-east1 --project=$PROJECT_ID --quiet; then
      echo "Error: Invalid Cloud Deploy configuration"
      exit 1
    fi

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA', '.']

# Run security scan on the container
- name: 'gcr.io/cloud-builders/docker'
  args: ['scan', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA']

# Tag the image as latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:latest']

# Push the latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:latest']

# Create source archive for Cloud Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Creating source archive..."
    tar -czf /workspace/source.tar.gz skaffold.yaml k8s/

# Create a new release in Cloud Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'releases'
  - 'create'
  - 'rel-${SHORT_SHA}'
  - '--delivery-pipeline=myportfoliowebsite'
  - '--region=asia-east1'
  - '--images=portfolio=asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA'
  - '--source=/workspace/source.tar.gz'
  - '--quiet'
  - '--to-target=newportfolio-prod'

# Verify deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'releases'
  - 'describe'
  - 'rel-${SHORT_SHA}'
  - '--delivery-pipeline=myportfoliowebsite'
  - '--region=asia-east1'
  - '--quiet'

images:
- 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA'
- 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true
  env:
  - 'CLOUD_LOGGING_ONLY=true'
  - 'DOCKER_BUILDKIT=1' 