steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA']

# Tag the image as latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:latest']

# Push the latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:latest']

# Apply simplified Cloud Deploy configuration (pipeline and target)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'apply'
  - '--file=clouddeploy.yaml'
  - '--region=asia-east1'
  - '--project=$PROJECT_ID'

# Update the pipeline to add executionConfigs using bash
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'delivery-pipelines'
  - 'patch'
  - 'myportfoliowebsite'
  - '--region=asia-east1'
  - '--execution-configs=usages=RENDER,DEPLOY,serviceAccount=622922749626-compute@developer.gserviceaccount.com,executionTimeout=3600s'
  - '--project=$PROJECT_ID'

# Create source archive for Cloud Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    tar -czf /workspace/source.tar.gz skaffold.yaml k8s/

# Create a new release in Cloud Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'releases'
  - 'create'
  - 'rel-${SHORT_SHA}'
  - '--delivery-pipeline=myportfoliowebsite'
  - '--region=asia-east1'
  - '--images=portfolio=asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA'
  - '--source=/workspace/source.tar.gz'

images:
- 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:$COMMIT_SHA'
- 'asia-south2-docker.pkg.dev/$PROJECT_ID/portfolio-docker-repo/portfolio:latest'

options:
  logging: CLOUD_LOGGING_ONLY 