apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: portfolio
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml AC