apiVersion: v1
kind: Service
metadata:
  name: portfolio-website
  labels:
    app: portfolio-website
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: portfolio-website 