apiVersion: v1
kind: Service
metadata:
  name: myportfoliowebsite-target-1
  labels:
    app: myportfoliowebsite-target-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: myportfoliowebsite-target-1 